# -*- coding: utf-8 -*-
"""Physics Informed Neural Network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAZVIENWZ2rkgKuMKMUbJVBtm54Bu5aA

# 1. PINNs

---

## 1.1. Heat-Neumann Equation

Solve the 1D heat equation: $u_t = \alpha u_{xx}$ for $x$ in [0, 1], $t$ in [0, 1], with initial condition $u(x, 0) = \cos(\pi x)$, boundary conditions $u_x(0,t) = 0$, $u_x(1,t) = 0$.
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# Parameters
alpha = 1e-2
domain_x = [0, 1]
domain_t = [0, 1]

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    u = model(inputs)
    u_t = tape.gradient(u, t)
    u_x = tape.gradient(u, x)
  u_xx = tape.gradient(u_x, x)
  del tape
  return u_t - alpha * u_xx

# Boundary condition loss (Neumann)
def bc_loss(model):
  t = tf.random.uniform(
    (50, 1),
    domain_t[0],
    domain_t[1]
  )
  x_left = tf.zeros_like(t)
  x_right = tf.ones_like(t)
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x_left)
    tape.watch(x_right)
    inputs_left = tf.concat([x_left, t], axis=1)
    inputs_right = tf.concat([x_right, t], axis=1)
    u_left = model(inputs_left)
    u_right = model(inputs_right)
  u_x_left = tape.gradient(u_left, x_left)
  u_x_right = tape.gradient(u_right, x_right)
  del tape
  return tf.reduce_mean(
      tf.square(u_x_left)
  ) + tf.reduce_mean(
      tf.square(u_x_right)
  )

# Initial condition loss
def ic_loss(model):
  x = tf.random.uniform(
      (50, 1),
      domain_x[0],
      domain_t[1]
  )
  t = tf.zeros_like(x)
  inputs = tf.concat([x, t], axis=1)
  u = model(inputs)
  u_ic = tf.cos(np.pi * x)
  return tf.reduce_mean(tf.square(u-u_ic))

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
for epoch in range(1000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, Loss: {loss.numpy()}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  u_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': u_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(id_vars=['x', 'Time'], var_name='Solution Type', value_name='u')
fig = px.line(df_melted, x='x', y='u', animation_frame='Time', color='Solution Type',
              title='1D Heat Equation Solution Over Time')
fig.update_layout(
    xaxis_title='x',
    yaxis_title='u(x, t)'
)
fig.show()

"""## 1.2. Wave-Dirichlet Equation

Solve the 1D heat equation: $u_{tt} = c^2 u_{xx}$ for $x$ in [0, 1], $t$ in [0, 1], with initial condition $u(x, 0) = \sin(\pi x)$, $u_t(x,0) = 0$, boundary conditions $u_x(0,t) = 0$, $u_x(1,t) = 0$.
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# Parameters
c = 1.0
domain_x = [0, 1]
domain_t = [0, 1]

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape1:
    tape1.watch(x)
    tape1.watch(t)
    inputs = tf.concat([x, t], axis=1)
    u = model(inputs)
    u_t = tape1.gradient(u, t)
    u_x = tape1.gradient(u, x)
  u_xx = tape1.gradient(u_x, x)
  u_tt = tape1.gradient(u_t, t)
  del tape1
  return u_tt - c**2 * u_xx

# Boundary condition loss
def bc_loss(model):
  t = tf.random.uniform((50, 1), domain_t[0], domain_t[1])
  x_left = tf.zeros_like(t)
  x_right = tf.ones_like(t)
  inputs_left = tf.concat([x_left, t], axis=1)
  inputs_right = tf.concat([x_right, t], axis=1)
  u_left = model(inputs_left)
  u_right = model(inputs_right)
  return tf.reduce_mean(tf.square(u_left)) + tf.reduce_mean(tf.square(u_right))

# Initial condition loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  with tf.GradientTape() as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    u = model(inputs)
  u_t = tape.gradient(u, t)
  u_ic = tf.sin(np.pi * x)
  u_t_ic = tf.zeros_like(x)
  return tf.reduce_mean(tf.square(u-u_ic)) + tf.reduce_mean(tf.square(u_t - u_t_ic))

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
for epoch in range(1000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, Loss: {loss.numpy()}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  u_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': u_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(id_vars=['x', 'Time'], var_name='Solution Type', value_name='u')
fig = px.line(df_melted, x='x', y='u', animation_frame='Time', color='Solution Type',
              title='1D Wave Equation Solution Over Time')
fig.update_layout(
  xaxis_title='x',
  yaxis_title='u(x, t)'
)
fig.show()

"""## 1.3. Advection Equation

Solve the 1D advection equation: $u_{t} + v u_x = 0$ for $x$ in [0, 1], $t$ in [0, 1], with initial condition $u(x, 0) = e^{-\left(\frac{(x-0.5)^2}{0.01}\right)}$, periodic boundary conditions.
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# Parameters
v = 1.0
domain_x = [0, 1]
domain_t = [0, 1]

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    u = model(inputs)
    u_x = tape.gradient(u, x)
    u_t = tape.gradient(u, t)
  del tape
  return u_t + v*u_x

# Boundary Condition loss (periodic)
def bc_loss(model):
  t = tf.random.uniform((50, 1), domain_t[0], domain_t[1])
  x_left = tf.zeros_like(t)
  x_right = tf.ones_like(t)
  inputs_left = tf.concat([x_left, t], axis=1)
  inputs_right = tf.concat([x_right, t], axis=1)
  u_left = model(inputs_left)
  u_right = model(inputs_right)
  return tf.reduce_mean(tf.square(u_left - u_right))

# Initial Condition Loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  inputs = tf.concat([x, t], axis=1)
  u = model(inputs)
  u_ic = tf.exp(-((x-0.5)**2)/(0.01))
  return tf.reduce_mean(tf.square(u-u_ic))

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
for epoch in range(1000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, Loss: {loss.numpy()}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:,None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  u_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': u_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(id_vars=['x', 'Time'], var_name='Solution Type', value_name='u')
fig = px.line(df_melted, x='x', y='u', animation_frame='Time', color='Solution Type',
              title='1D Advection Equation Solution Over Time')
fig.update_layout(
    xaxis_title='x',
    yaxis_title='u(x, t)'
)
fig.show()

"""## 1.4. Burgers Equation

Solve the 1D Burgers' equation: $u_{t} + u u_x = \nu u_{xx}$ for $x$ in [0, 1], $t$ in [0, 1], with initial condition $u(x, 0) = -\sin(\pi x)$, periodic boundary conditions.
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# Parameters
nu = 0.01 / np.pi
domain_x = [0, 1]
domain_t = [0, 1]

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    u = model(inputs)
    u_x = tape.gradient(u, x)
    u_t = tape.gradient(u, t)
  u_xx = tape.gradient(u_x, x)
  del tape
  return u_t + u*u_x - nu*u_xx

# Boundary Condition Loss (periodic)
def bc_loss(model):
  t = tf.random.uniform((50, 1), domain_t[0], domain_t[1])
  x_left = tf.zeros_like(t)
  x_right = tf.ones_like(t)
  inputs_left = tf.concat([x_left, t], axis=1)
  inputs_right = tf.concat([x_right, t], axis=1)
  u_left = model(inputs_left)
  u_right = model(inputs_right)
  return tf.reduce_mean(tf.square(u_left - u_right))

# Initial condition loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  inputs = tf.concat([x, t], axis=1)
  u = model(inputs)
  u_ic = -tf.sin(np.pi * x)
  return tf.reduce_mean(tf.square(u-u_ic))

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
for epoch in range(1000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, Loss: {loss.numpy()}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  u_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': u_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(
    id_vars=['x', 'Time'],
    var_name='Solution Type',
    value_name='u'
)
fig = px.line(
    df_melted,
    x = 'x',
    y = 'u',
    animation_frame='Time',
    color = 'Solution Type',
    title = '1D Burgers Equation Solution Over Time'
)
fig.update_layout(
    xaxis_title='x',
    yaxis_title='u(x, t)'
)
fig.show()

"""## 1.5. 1D Damped Wave Equation

Solve the 1D damped wave equation: $u_{tt} + \beta u_t = c^2 u_{xx}$ for $x$ in [0, 1], $t$ in [0, 1], with initial condition $u(x, 0) = \sin(\pi x)$, $u_t(x, 0) = 0$, boundary conditions $u(0,t) = 0$, $u(1,t)=0$.
"""

import tensorflow as tf
import numpy as np

# Parameters
c = 1.0
beta = 0.1
domain_x = [0,1]
domain_t = [0,1]

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape1:
    tape1.watch(x)
    tape1.watch(t)
    inputs = tf.concat([x, t], axis=1)
    u = model(inputs)
    u_t = tape1.gradient(u, t)
    u_x = tape1.gradient(u, x)
  u_xx = tape1.gradient(u_x, x)
  u_tt = tape1.gradient(u_t, t)
  del tape1
  return u_tt + beta*u_t - c**2 * u_xx

# Boundary condition loss
def bc_loss(model):
  t = tf.random.uniform((50, 1), domain_t[0], domain_t[1])
  x_left = tf.zeros_like(t)
  x_right = tf.ones_like(t)
  inputs_left = tf.concat([x_left, t], axis=1)
  inputs_right = tf.concat([x_right, t], axis=1)
  u_left = model(inputs_left)
  u_right = model(inputs_right)
  return tf.reduce_mean(
      tf.square(u_left) + tf.square(u_right)
  )

# Initial condition loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  with tf.GradientTape() as tape:
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    u = model(inputs)
    u_t = tape.gradient(u, t)
  u_ic = tf.sin(np.pi*x)
  u_t_ic = tf.zeros_like(x)
  return tf.reduce_mean(
      tf.square(u - u_ic) +
      tf.square(u_t - u_t_ic)
  )

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
for epoch in range(1000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, Loss: {loss.numpy()}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 100)[:, None]
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  u_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': u_plot.flatten(),
      'Time': t_val[0]
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(
    id_vars=['x', 'Time'],
    var_name='Solution Type',
    value_name='u'
)
fig = px.line(
    df_melted,
    x='x',
    y='u',
    animation_frame='Time',
    color='Solution Type',
    title='1D Damped Wave Equation Solution Over Time'
)
fig.update_layout(
    xaxis_title='x',
    yaxis_title='u(x, t)'
)
fig.show()

"""## 1.6. 1D KdV Equation

Solve the 1D KdV equation: $u_{t} + u u_x + \delta u_{xxx} = 0$ for $x$ in [0, 2], $t$ in [0, 1], with initial condition $u(x, 0) = \cos(\pi x)$, periodic boundary conditions.
"""

import tensorflow as tf
import numpy as np

# Parameters
delta = 0.022
domain_x = [0, 2]
domain_t = [0, 1]

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    u = model(inputs)
    u_t = tape.gradient(u, t)
    u_x = tape.gradient(u, x)
    u_xx = tape.gradient(u_x, x)
  u_xxx = tape.gradient(u_xx, x)
  del tape
  return u_t + u*u_x + delta*u_xxx

# Boundary Condition Loss
def bc_loss(model):
  t = tf.random.uniform((50, 1), domain_t[0], domain_t[1])
  x_left = tf.zeros_like(t)
  x_right = tf.ones_like(t) * 2
  inputs_left = tf.concat([x_left, t], axis=1)
  inputs_right = tf.concat([x_right, t], axis=1)
  u_left = model(inputs_left)
  u_right = model(inputs_right)
  return tf.reduce_mean(tf.square(u_left - u_right))

# Initial condition loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  inputs = tf.concat([x, t], axis=1)
  u = model(inputs)
  u_ic = tf.cos(np.pi * x)
  return tf.reduce_mean(tf.square(u-u_ic))

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
for epoch in range(1000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, Loss: {loss.numpy()}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  u_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': u_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(
    id_vars=['x', 'Time'],
    var_name='Solution Type',
    value_name='u'
)

fig = px.line(
    df_melted,
    x='x',
    y='u',
    animation_frame='Time',
    color='Solution Type',
    title='1D KdV Equation Solution Over Time'
)
fig.update_layout(
    xaxis_title='x',
    yaxis_title='u(x, t)'
)
fig.show()

"""## 1.7. 1D Diffusion Equation

Solve the 1D diffusion equation: $u_{t} = \alpha u_{xx}$ for $x$ in [0, 1], $t$ in [0, 1], with initial condition $u(x, 0) = x (1-x)$, Robin boundary conditions: $u_x(0,t) + a u(0,t) = 0$, $u_x(1,t) + b u(1, t) = 0$.
"""

import tensorflow as tf
import numpy as np

# Parameters
alpha = 0.01
a = 1.0
b = 1.0
domain_x = [0, 1]
domain_t = [0, 1]

# Neural network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# PDE residual
def pde_residual(model):
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    u = model(inputs)
    u_x = tape.gradient(u, x)
    u_t = tape.gradient(u, t)
  u_xx = tape.gradient(u_x, x)
  del tape
  return u_t - alpha * u_xx

# Boundary condition loss
def bc_loss(model):
  t = tf.random.uniform((50, 1), domain_t[0], domain_t[1])
  x_left = tf.zeros_like(t)
  x_right = tf.ones_like(t)
  with tf.GradientTape(persistent=True) as tape1:
    tape1.watch(x_left)
    tape1.watch(x_right)
    inputs_left = tf.concat([x_left, t], axis=1)
    inputs_right = tf.concat([x_right, t], axis=1)
    u_left = model(inputs_left)
    u_right = model(inputs_right)
    u_x_left = tape1.gradient(u_left, x_left)
    u_x_right = tape1.gradient(u_right, x_right)
  del tape1
  robin_left = u_x_left + a * u_left
  robin_right = u_x_right + b * u_right
  return tf.reduce_mean(
      tf.square(robin_left) + tf.square(robin_right)
  )

# Initial condition loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  inputs = tf.concat([x, t], axis=1)
  u = model(inputs)
  u_ic = x * (1 - x)
  return tf.reduce_mean(tf.square(u - u_ic))

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
for epoch in range(1000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 500 == 0:
    print(f"Epoch {epoch}, loss: {loss.numpy()}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  u_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': u_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(
    id_vars=['x', 'Time'],
    var_name='Solution Type',
    value_name='u'
)
fig = px.line(
    df_melted,
    x='x',
    y='u',
    animation_frame='Time',
    color='Solution Type',
    title='1D Diffusion Equation Solution Over Time'
)
fig.update_layout(
    xaxis_title='x',
    yaxis_title='u(x, t)'
)
fig.show()

"""## 1.8. Advection-Diffusion Equation

Solve the 1D advection-diffusion equation: $u_{t} + v u_x = \kappa u_{xx}$ for $x$ in [0, 1], $t$ in [0, 1], with initial condition $u(x, 0) = \sin(2\pi x)$, boundary conditions $u(0, t) = 0$, $u(1, t) = 0$.
"""

import tensorflow as tf
import numpy as np

# Parameters
v = 1.0
kappa = 1e-2
domain_x = [0, 1]
domain_t = [0, 1]

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    u = model(inputs)
    u_x = tape.gradient(u, x)
    u_t = tape.gradient(u, t)
  u_xx = tape.gradient(u_x, x)
  del tape
  return u_t + v * u_x - kappa * u_xx

# Boundary Condition loss
def bc_loss(model):
  t = tf.random.uniform((50, 1), domain_t[0], domain_t[1])
  x_left = tf.zeros_like(t)
  x_right = tf.ones_like(t)
  inputs_left = tf.concat([x_left, t], axis=1)
  inputs_right = tf.concat([x_right, t], axis=1)
  u_left = model(inputs_left)
  u_right = model(inputs_right)
  return tf.reduce_mean(tf.square(u_left)) + tf.reduce_mean(
      tf.square(u_right)
  )

# Initial Condition loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  inputs = tf.concat([x, t], axis=1)
  u = model(inputs)
  u_ic = tf.sin(2 * np.pi * x)
  return tf.reduce_mean(tf.square(u - u_ic))

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
for epoch in range(1000): # Need to increase the epochs
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_ic + loss_bc
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, loss: {loss.numpy()}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  u_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': u_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(
    id_vars=['x', 'Time'],
    var_name='Solution Type',
    value_name='u'
)
fig = px.line(
    df_melted,
    x = 'x',
    y = 'u',
    animation_frame = 'Time',
    color = 'Solution Type',
    title = '1D Advection-Diffusion Equation Solution Over Time'
)
fig.update_layout(
    xaxis_title = 'x',
    yaxis_title = 'u(x, t)'
)
fig.show()

"""## 1.9. Fisher-KPP equation

Solve the 1D Fisher-KPP equation: $u_{t} = D u_{xx} + r u (1-u)$ for $x$ in [0, 1], $t$ in [0, 1], with initial condition $u(x, 0) = \frac{1+\sin(2\pi x)}{2}$, boundary conditions $u_x(0, t) = 0$, $u_x(1, t) = 0$.
"""

import tensorflow as tf
import numpy as np

# Parameters
D = 1e-2
r = 1.0
domain_x = [0, 1]
domain_t = [0, 1]

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    u = model(inputs)
    u_x = tape.gradient(u, x)
    u_t = tape.gradient(u, t)
  u_xx = tape.gradient(u_x, x)
  del tape
  return u_t + D * u_xx + r * u * (1-u)

# Boundary condition loss ( Neumann )
def bc_loss(model):
  t = tf.random.uniform((50, 1), domain_t[0], domain_t[1])
  x_left = tf.zeros_like(t)
  x_right = tf.ones_like(t)
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x_left)
    tape.watch(x_right)
    inputs_left = tf.concat([x_left, t], axis=1)
    inputs_right = tf.concat([x_right, t], axis=1)
    u_left = model(inputs_left)
    u_right = model(inputs_right)
  u_x_left = tape.gradient(u_left, x_left)
  u_x_right = tape.gradient(u_right, x_right)
  del tape
  return tf.reduce_mean(
      tf.square(u_x_left) + tf.square(u_x_right)
  )

# Initial condition loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  inputs = tf.concat([x, t], axis=1)
  u = model(inputs)
  u_ic = (1 + tf.sin(2 * np.pi * x)) / 2
  return tf.reduce_mean(tf.square(u - u_ic))

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
for epoch in range(1000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, loss: {loss.numpy()}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  u_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': u_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(
    id_vars=['x', 'Time'],
    var_name='Solution Type',
    value_name='u'
)

fig = px.line(
    df_melted,
    x='x',
    y='u',
    animation_frame='Time',
    color='Solution Type',
    title='1D Fisher-KPP Equation Solution Over Time'
)

fig.update_layout(
    xaxis_title='x',
    yaxis_title='u(x, t)'
)
fig.show()

"""## 1.10. Allen-Cahn Equation

Solve the 1D Allen-Cahn equation: $u_{t} = \epsilon^2 u_{xx} + u - u^3$ for $x$ in [-1, 1], $t$ in [0, 1], with initial condition $u(x, 0) = x^2\cos(\pi x)$, periodic boundary conditions.
"""

import tensorflow as tf
import numpy as np

# Parameters
epsilon = 0.1
domain_x = [-1, 1]
domain_t = [0, 1]

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    u = model(inputs)
    u_x = tape.gradient(u, x)
    u_t = tape.gradient(u, t)
  u_xx = tape.gradient(u_x, x)
  del tape
  return u_t + epsilon**2 * u_xx - (u - u**3)

# boundary condition loss (periodic)
def bc_loss(model):
  t = tf.random.uniform((50, 1), domain_t[0], domain_t[1])
  x_left = tf.zeros_like(t)
  x_right = tf.ones_like(t)
  inputs_left = tf.concat([x_left, t], axis=1)
  inputs_right = tf.concat([x_right, t], axis=1)
  u_left = model(inputs_left)
  u_right = model(inputs_right)
  return tf.reduce_mean(tf.square(u_left - u_right))

# initial condition loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  inputs = tf.concat([x, t], axis=1)
  u = model(inputs)
  u_ic = x**2 * tf.cos(np.pi * x)
  return tf.reduce_mean(tf.square(u - u_ic))

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
for epoch in range(1000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, loss: {loss.numpy()}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  u_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': u_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(
    id_vars=['x', 'Time'],
    var_name = 'Solution Type',
    value_name = 'u'
)

fig = px.line(
    df_melted,
    x = 'x',
    y = 'u',
    animation_frame = 'Time',
    color = 'Solution Type',
    title = '1D Allen-Cahn Equation SOlution over Time',
)

fig.update_layout(
    xaxis_title = 'x',
    yaxis_title = 'u(x, t)'
)
fig.show()

"""## 1.11. Battery Thermal Behavior

Model battery thermal behavior: $T_t = \alpha T_{xx} + Q(I, t)$, where Q is heat source ($Q(I, t) = 0.1 \sin(2 \pi t)$) from current $I$, for $x$ in [0, 1], $t$ in [0, 1], with initial condition $T(x, 0) = 300 + 10\sin(\pi x)$, boundary conditions $T(0, t) = 300$, $T_x(1, t) = 0$.
"""

import tensorflow as tf
import numpy as np

# Parameters
alpha = 1e-2
domain_x = [0, 1]
domain_t = [0, 1]

def heat_source(x, t):
  return 0.1 * tf.sin(2*np.pi*t) # Q(I, t)

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(64, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(32, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    T = model(inputs)
    T_t = tape.gradient(T, t)
    T_x = tape.gradient(T, x)
  T_xx = tape.gradient(T_x, x)
  del tape
  return T_t - alpha * T_xx - heat_source(x, t)

# Boundary Condition Loss
def bc_loss(model):
  t = tf.random.uniform((50, 1), domain_t[0], domain_t[1])
  x_left = tf.zeros_like(t)
  inputs_left = tf.concat([x_left, t], axis=1)
  T_left = model(inputs_left)
  loss_left = tf.reduce_mean(tf.square(T_left - 300.0)) # Corrected loss for T(0, t) = 300
  x_right = tf.ones_like(t)
  with tf.GradientTape() as tape:
    tape.watch(x_right)
    inputs_right = tf.concat([x_right, t], axis=1)
    T_right = model(inputs_right)
  T_x_right = tape.gradient(T_right, x_right)
  del tape
  loss_right = tf.reduce_mean(tf.square(T_x_right)) # Loss for T_x(1, t) = 0
  return loss_left + loss_right

# Initial condition loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  inputs = tf.concat([x, t], axis=1)
  T = model(inputs)
  T_ic = 300.0 + 10.0 * tf.sin(np.pi * x) # Corrected loss for T(x, 0)
  return tf.reduce_mean(tf.square(T - T_ic))

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-2)
for epoch in range(2000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, loss: {loss}")

optimizer = tf.keras.optimizers.Adam(learning_rate=1e-4)
for epoch in range(1000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, loss: {loss}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  T_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': T_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(
    id_vars=['x', 'Time'],
    var_name = 'Solution Type',
    value_name = 'T'
)

fig = px.line(
    df_melted,
    x = 'x',
    y = 'T',
    animation_frame = 'Time',
    color = 'Solution Type',
    title = '1D Battery Thermal Behavior Solution Over Time'
)

fig.update_layout(
    xaxis_title = 'x',
    yaxis_title = 'T(x, t)'
)
fig.show()

"""## 1.12. State of Charge Equation

Solve the 1D SOC equation: $c_{t} = D c_{xx} - kc$ for $x$ in [0, 1], $t$ in [0, 1], with initial condition $c(x, 0) = \frac{1+\sin(\pi x)}{2}$, boundary conditions $x(0, t) = 1$, $c_x(1, t) = 0$.
"""

import tensorflow as tf
import numpy as np

# Parameters
D = 1e-3
k = 0.1
domain_x = [0, 1]
domain_t = [0, 1]

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    c = model(inputs)
    c_x = tape.gradient(c, x)
    c_t = tape.gradient(c, t)
  c_xx = tape.gradient(c_x, x)
  del tape
  return c_t - D * c_xx + k * c

# Boundary Condition loss
def bc_loss(model):
  t = tf.random.uniform((50, 1), domain_t[0], domain_t[1])
  x_left = tf.zeros_like(t)
  inputs_left = tf.concat([x_left, t], axis=1)
  c_left = model(inputs_left)
  loss_left = tf.reduce_mean(tf.square(c_left - 1.0))
  x_right = tf.ones_like(t)
  with tf.GradientTape() as tape:
    tape.watch(x_right)
    inputs_right = tf.concat([x_right, t], axis=1)
    c_right = model(inputs_right)
  c_x_right = tape.gradient(c_right, x_right)
  del tape
  loss_right = tf.reduce_mean(tf.square(c_x_right))
  return loss_left + loss_right

# Initial COndition Loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  inputs = tf.concat([x, t], axis=1)
  c = model(inputs)
  c_ic = (1 + tf.sin(np.pi * x)) / 2
  return tf.reduce_mean(tf.square(c - c_ic))

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
for epoch in range(1000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, loss: {loss}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  c_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': c_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(
    id_vars=['x', 'Time'],
    var_name = 'Solution Type',
    value_name = 'c'
)

fig = px.line(
    df_melted,
    x = 'x',
    y = 'c',
    animation_frame = 'Time',
    color = 'Solution Type',
    title = '1D State of Charge Equation Solution Over Time'
)

fig.update_layout(
    xaxis_title = 'x',
    yaxis_title = 'c(x, t)'
)
fig.show()

"""## 1.13. Population Diffusion Equation

Solve the population diffusion equations: $p_t = Dp_{xx} + r p (1-\frac{p}{K})$, for $x$ in [0,1], $t$ in [0,1], initial $p(x, 0) = \frac{K}{2} + \frac{K}{2} \sin(\pi x)$, boundary conditions $p_x(0,t)=0$, $p_x(1,t)=0$.
"""

import tensorflow as tf
import numpy as np

# Parameters
D = 1e-2
r = 0.5
K = 1.0
domain_x = [0, 1]
domain_t = [0, 1]

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return K * tf.nn.sigmoid(self.dense3(x))

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    p = model(inputs)
    p_t = tape.gradient(p, t)
    p_x = tape.gradient(p, x)
  p_xx = tape.gradient(p_x, x)
  del tape
  return p_t - D * p_xx - r * p * (1-p/K)

# Boundary condition loss
def bc_loss(model):
  t = tf.random.uniform((50, 1), domain_t[0], domain_t[1])
  x_left = tf.zeros_like(t)
  x_right = tf.ones_like(t)
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x_left)
    tape.watch(x_right)
    inputs_left = tf.concat([x_left, t], axis=1)
    inputs_right = tf.concat([x_right, t], axis=1)
    p_left = model(inputs_left)
    p_right = model(inputs_right)
  p_x_left = tape.gradient(p_left, x_left)
  p_x_right = tape.gradient(p_right, x_right)
  del tape
  return tf.reduce_mean(
      tf.square(p_x_left) + tf.square(p_x_right)
  )

# Initial condition loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  inputs = tf.concat([x, t], axis=1)
  p = model(inputs)
  p_ic = (K / 2) + (K / 2) * tf.sin(np.pi * x)
  return tf.reduce_mean(tf.square(p-p_ic))

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
for epoch in range(1000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, loss: {loss}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  p_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': p_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(
    id_vars=['x', 'Time'],
    var_name = 'Solution Type',
    value_name = 'p'
)

fig = px.line(
    df_melted,
    x = 'x',
    y = 'p',
    animation_frame = 'Time',
    color = 'Solution Type',
    title = '1D Population Diffusion Equation Solution Over Time'
)

fig.update_layout(
    xaxis_title = 'x',
    yaxis_title = 'p(x, t)'
)

fig.show()

"""## 1.14. Anomaly Wave Equation

Model anomaly in battery as wave: $a_{tt} = c^2 a_{xx}$, for x in [0, 1], t in [0, 1], initial $a(x, 0) = \exp{\frac{-(x-0.5)^2}{0.01}}$, $a_t = 0$, boundary $a(0, t) = 0$, $a(1, t) = 0$.
"""

import tensorflow as tf
import numpy as np

# Parameters
c = 0.5
domain_x = [0, 1]
domain_t = [0, 1]

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    a = model(inputs)
    a_t = tape.gradient(a, t)
    a_x = tape.gradient(a, x)
  a_xx = tape.gradient(a_x, x)
  a_tt = tape.gradient(a_t, t)
  del tape
  return a_tt - c**2 * a_xx

# Boundary condition loss
def bc_loss(model):
  t = tf.random.uniform((50,1), domain_t[0], domain_t[1])
  x_left = tf.zeros_like(t)
  x_right = tf.ones_like(t)
  inputs_left = tf.concat([x_left, t], axis=1)
  inputs_right = tf.concat([x_right, t], axis=1)
  a_left = model(inputs_left)
  a_right = model(inputs_right)
  return tf.reduce_mean(
      tf.square(a_left)
  ) + tf.reduce_mean(
      tf.square(a_right)
  )

# Initial condition loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  with tf.GradientTape() as tape1:
    tape1.watch(t)
    inputs = tf.concat([x, t], axis=1)
    a = model(inputs)
    a_t = tape1.gradient(a, t)
  a_ic = tf.exp(-(x-0.5)**2/0.01)
  a_t_ic = tf.zeros_like(x)
  e1 = tf.square(a-a_ic)
  e2 = tf.square(a_t-a_t_ic)
  return tf.reduce_mean(e1) + tf.reduce_mean(e2)

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-4)
for epoch in range(5000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, Loss: {loss.numpy()}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  a_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': a_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(
    id_vars=['x', 'Time'],
    var_name = 'Solution Type',
    value_name = 'a'
)

fig = px.line(
    df_melted,
    x = 'x',
    y = 'a',
    animation_frame = 'Time',
    color = 'Solution Type',
    title = '1D Anomaly Wave Equation Solution Over Time'
)

fig.update_layout(
    xaxis_title = 'x',
    yaxis_title = 'a(x, t)'
)

"""## 1.15. Thermal Runaway Equation

Model thermal runaway: $T_t = \alpha T_{xx} + \beta e^{-\frac{E}{T}}$, for x in [0,1], t in [0,1], initial $T(x,0) = 300 + 50x$, boundary $T(0,t) = 300$, $T(1,t) = 350$.
"""

import tensorflow as tf
import numpy as np

# Parameters
alpha = 0.01
beta = 1e5
E = 1000
domain_x = [0,1]
domain_t = [0,1]

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return 300 + 50 * tf.nn.sigmoid(self.dense3(x))

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    T = model(inputs)
    T_t = tape.gradient(T, t)
    T_x = tape.gradient(T, x)
  T_xx = tape.gradient(T_x, x)
  del tape
  return T_t - alpha * T_xx - beta * tf.exp(-E/T)

# Boundary condition loss
def bc_loss(model):
  t = tf.random.uniform((50, 1), domain_t[0], domain_t[1])
  x_left = tf.zeros_like(t)
  inputs_left = tf.concat([x_left, t], axis=1)
  T_left = model(inputs_left)
  loss_left = tf.reduce_mean(tf.square(T_left - 300))
  x_right = tf.ones_like(t)
  inputs_right = tf.concat([x_right, t], axis=1)
  T_right = model(inputs_right)
  loss_right = tf.reduce_mean(tf.square(T_right - 350))
  return loss_left + loss_right

# Initial condition loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  inputs = tf.concat([x, t], axis=1)
  T = model(inputs)
  T_ic = 300 + 50 * x
  return tf.reduce_mean(tf.square(T - T_ic))

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate = 0.1)
for epoch in range(1000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual)) / 1e4
    loss_bc = bc_loss(model) / 1e4
    loss_ic = ic_loss(model) / 1e4
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, loss: {loss}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  T_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': T_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(
    id_vars=['x', 'Time'],
    var_name = 'Solution Type',
    value_name = 'T'
)
fig = px.line(
    df_melted,
    x = 'x',
    y = 'T',
    animation_frame = 'Time',
    color = 'Solution Type',
    title = '1D Thermal Runaway Equation Solution Over Time'
)

fig.update_layout(
    xaxis_title = 'x',
    yaxis_title = 'T(x, t)'
)

"""## 1.16. Fokker Planck Equation

Fokker-Planck: $p_t = - (\mu p)_x + (D p)_{xx}$, for x in [-2,2], t in [0,1], initial $p(x,0) = \frac{e^{-\frac{x^2}{0.1}}}{\sqrt{\pi*0.1}}$, periodic boundary.
"""

import tensorflow as tf
import numpy as np

# Parameters
mu = lambda x: -x # Drift
D = 0.1
domain_x = [-2, 2]
domain_t = [0, 1]

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return tf.nn.softplus(self.dense3(x))

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    p = model(inputs)
    p_t = tape.gradient(p, t)
    p_x = tape.gradient(p, x)
  p_xx = tape.gradient(p_x, x)
  del tape
  return p_t - mu(x) * p_x - D * p_xx

# Boundary condition loss
def bc_loss(model):
  t = tf.random.uniform((50, 1), domain_t[0], domain_t[1])
  x_left = -2 * tf.ones_like(t)
  x_right = 2 * tf.ones_like(t)
  inputs_left = tf.concat([x_left, t], axis=1)
  inputs_right = tf.concat([x_right, t], axis=1)
  p_left = model(inputs_left)
  p_right = model(inputs_right)
  return tf.reduce_mean(tf.square(p_left - p_right))

# Initial condition loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  inputs = tf.concat([x, t], axis=1)
  p = model(inputs)
  p_ic = tf.exp(-x**2/0.1) / tf.sqrt(np.pi*0.1)
  return tf.reduce_mean(tf.square(p-p_ic))

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
for epoch in range(1000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + 10*loss_bc + 10*loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, loss: {loss}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  p_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': p_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(
    id_vars=['x', 'Time'],
    var_name = 'Solution Type',
    value_name = 'p'
)

fig = px.line(
    df_melted,
    x = 'x',
    y = 'p',
    animation_frame = 'Time',
    color = 'Solution Type',
    title = '1D Fokker-Planck Equation Solution Over Time'
)

fig.update_layout(
    xaxis_title = 'x',
    yaxis_title = 'p(x, t)'
)

"""## 1.17. Fluid Pipe Equation

Model 1D fluid in pipe: $v_t + v v_x = \nu v_{xx}$, for x in [0,1], t in [0,1], initial $v(x,0) = \sin(\pi x)$, boundary $v(0, t) = 0$, $v(1, t) = 0$.
"""

import tensorflow as tf
import numpy as np

# Parameters
nu = 0.01
domain_x = [0,1]
domain_t = [0,1]

# Neural Network
class PINN(tf.keras.Model):
  def __init__(self):
    super(PINN, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh')
    self.dense3 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# PDE residual
def pde_residual(model, x, t):
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    tape.watch(t)
    inputs = tf.concat([x, t], axis=1)
    v = model(inputs)
    v_t = tape.gradient(v, t)
    v_x = tape.gradient(v, x)
  v_xx = tape.gradient(v_x, x)
  del tape
  return v_t + v * v_x - nu * v_xx

# Boundary condition loss
def bc_loss(model):
  t = tf.random.uniform((50, 1), domain_t[0], domain_t[1])
  x_left = tf.zeros_like(t)
  x_right = tf.ones_like(t)
  inputs_left = tf.concat([x_left, t], axis=1)
  inputs_right = tf.concat([x_right, t], axis=1)
  v_left = model(inputs_left)
  v_right = model(inputs_right)
  return tf.reduce_mean(tf.square(v_left)) + tf.reduce_mean(tf.square(v_right))

# Initial condition loss
def ic_loss(model):
  x = tf.random.uniform((50, 1), domain_x[0], domain_x[1])
  t = tf.zeros_like(x)
  inputs = tf.concat([x, t], axis=1)
  v = model(inputs)
  v_ic = tf.sin(np.pi * x)
  return tf.reduce_mean(tf.square(v - v_ic))

# Training
model = PINN()
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
for epoch in range(2000):
  x = tf.random.uniform((100, 1), domain_x[0], domain_x[1])
  t = tf.random.uniform((100, 1), domain_t[0], domain_t[1])
  with tf.GradientTape() as tape:
    residual = pde_residual(model, x, t)
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_bc = bc_loss(model)
    loss_ic = ic_loss(model)
    loss = loss_pde + loss_bc + loss_ic
  grads = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(grads, model.trainable_variables))
  if epoch % 50 == 0:
    print(f"Epoch {epoch}, loss: {loss}")

import plotly.express as px
import pandas as pd

time_steps = np.linspace(domain_t[0], domain_t[1], 51)
plot_data = []

for t_val in time_steps:
  x_plot = np.linspace(domain_x[0], domain_x[1], 100)[:, None]
  t_plot = t_val * np.ones_like(x_plot)
  inputs_plot = np.concatenate([x_plot, t_plot], axis=1)
  v_plot = model(inputs_plot).numpy()
  df_temp = pd.DataFrame({
      'x': x_plot.flatten(),
      'PINN': v_plot.flatten(),
      'Time': t_val
  })
  plot_data.append(df_temp)

df_plot = pd.concat(plot_data)
df_melted = df_plot.melt(
    id_vars=['x', 'Time'],
    var_name = 'Solution Type',
    value_name = 'v'
)

fig = px.line(
    df_melted,
    x = 'x',
    y = 'v',
    animation_frame = 'Time',
    color = 'Solution Type',
    title = '1D Fluid Pipe Equation Solution Over Time'
)

fig.update_layout(
    xaxis_title = 'x',
    yaxis_title = 'v(x, t)'
)

"""# 2. Inverse PINNs

---

## 2.1. 1D Heat Inference Equation

Given the data from $u_t = \alpha u_{xx}$, infer $\alpha$ from the data.

Generate the data from $\alpha=0.01$, $u(x, 0) = \sin(\pi x)$, $u(0, t) = 0$, $u(1, t) = 0$.
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# Generate Synthetic Data
domain_x = [0, 1]
domain_t = [0, 1]
alpha_true = 0.01

# Create the 20x20 grid
x_space = np.linspace(domain_x[0], domain_x[1], 20)
t_space = np.linspace(domain_t[0], domain_t[1], 20)
X, T = np.meshgrid(x_space, t_space)
u_data = np.sin(np.pi * X) * np.exp(-alpha_true * np.pi**2 * T)

X_flat = X.flatten()[:, None] # Shape (400, 1)
T_flat = T.flatten()[:, None] # Shape (400, 1)
u_flat = u_data.flatten()[:, None] # Shape (400, 1)

# Convert to Tensorflow tensors
X_tf = tf.convert_to_tensor(X_flat, dtype=tf.float32)
T_tf = tf.convert_to_tensor(T_flat, dtype=tf.float32)
u_tf = tf.convert_to_tensor(u_flat, dtype=tf.float32)

# Neural Network for inference
class InferModel(tf.keras.Model):
  def __init__(self):
    super(InferModel, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh', kernel_initializer='glorot_normal')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh', kernel_initializer='glorot_normal')
    self.dense3 = tf.keras.layers.Dense(1)
    # Initialize alpha with a guess, make it trainable
    self.alpha = self.add_weight(
        name = 'alpha',
        shape = (), # It's a scalar
        initializer = tf.keras.initializers.Constant(0.05), # initial guess
        trainable = True,
        dtype = tf.float32
    )

  def call(self, inputs):
    # inputs will be (x, t) pairs, shape (N, 2)
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# Training
model_infer = InferModel()
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
epochs = 2000
for epoch in range(epochs):
  with tf.GradientTape() as loss_tape:
    with tf.GradientTape(persistent=True) as tape2: # to compute derivates of u with respect to inputs
      tape2.watch(X_tf)
      tape2.watch(T_tf)
      with tf.GradientTape(persistent=True) as tape1: # to compute derivatives of u with respect to x and t
        tape1.watch(X_tf)
        tape1.watch(T_tf)
        inputs = tf.concat([X_tf, T_tf], axis=1) # Shape (400, 2)
        u_pred = model_infer(inputs) # Shape (400, 1)
      u_x = tape1.gradient(u_pred, X_tf)
      u_t = tape1.gradient(u_pred, T_tf)
      del tape1
    u_xx = tape2.gradient(u_x, X_tf)
    del tape2
    residual = u_t - model_infer.alpha * u_xx
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_data = tf.reduce_mean(tf.square(u_pred - u_tf))
    loss = loss_pde + loss_data
  grads = loss_tape.gradient(loss, model_infer.trainable_variables)
  optimizer.apply_gradients(zip(grads, model_infer.trainable_variables))
  if epoch % 200 == 0:
    if u_t is None or u_xx is None:
      print(f"Epoch {epoch}: Error")
      break
    print(f"Epoch {epoch}: Loss {loss.numpy():.4e}, Inferred Alpha {model_infer.alpha.numpy():.4f}")

print("-" * 30)
print(f"True alpha: {alpha_true}")
print(f"Inferred alpha: {model_infer.alpha.numpy():.4f}")

"""## 2.2. 1D Advection Equation

Given the data from $u_t + v u_x = 0$, infer $v$ from the data.

Generate the data from $v=1$, $u(x, 0) = e^{\frac{-(x-0.5)^2}{0.01}}$, periodic.
"""

import tensorflow as tf
import numpy as np

# Generating synthetic data
domain_x = [0.0, 1.0]
domain_t = [0.0, 1.0]
v_true = 1.0

x_space = np.linspace(domain_x[0], domain_x[1], 20)
t_space = np.linspace(domain_t[0], domain_t[1], 20)
X, T = np.meshgrid(x_space, t_space)

# Periodic Gaussian pulse advecting with speed v_true
width = 0.01
shifted = (X - 0.5 - v_true * T) % 1.0
u_data = np.exp(-((shifted - 0.5) ** 2) / width)

X_flat = X.flatten()[:, None]
T_flat = T.flatten()[:, None]
u_flat = u_data.flatten()[:, None]

X_tf = tf.convert_to_tensor(X_flat, dtype=tf.float32)
T_tf = tf.convert_to_tensor(T_flat, dtype=tf.float32)
u_tf = tf.convert_to_tensor(u_flat, dtype=tf.float32)

# Neural Network for inference
class InferModel(tf.keras.Model):
  def __init__(self):
    super(InferModel, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh', kernel_initializer='glorot_normal')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh', kernel_initializer='glorot_normal')
    self.dense3 = tf.keras.layers.Dense(1)
    self.v = self.add_weight(
        name = 'advection_speed_v',
        shape = (),
        initializer = tf.keras.initializers.Constant(0.5),
        trainable = True,
        dtype = tf.float32
    )

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# Training
model_infer = InferModel()
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

epochs = 2000
for epoch in range(epochs):
  with tf.GradientTape() as loss_tape:
    with tf.GradientTape(persistent=True) as tape2:
      tape2.watch(X_tf)
      tape2.watch(T_tf)
      with tf.GradientTape(persistent=True) as tape1:
        tape1.watch(X_tf)
        tape1.watch(T_tf)
        inputs = tf.concat([X_tf, T_tf], axis=1)
        u_pred = model_infer(inputs)
      u_x = tape1.gradient(u_pred, X_tf)
      u_t = tape1.gradient(u_pred, T_tf)
      del tape1
    del tape2
    residual = u_t + model_infer.v * u_x
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_data = tf.reduce_mean(tf.square(u_pred - u_tf))
    loss = loss_pde + loss_data

  grads = loss_tape.gradient(loss, model_infer.trainable_variables)
  optimizer.apply_gradients(zip(grads, model_infer.trainable_variables))
  if epoch % 200 == 0:
    if u_t is None or u_x is None:
      print(f"Epoch {epoch}: Error! Gradients are None. Check tape.watch().")
      break
    print(f"Epoch {epoch}: Loss {loss.numpy():.4e}, Inferred v {model_infer.v.numpy():.4f}")

print("-" * 30)
print(f"True v: {v_true}")
print(f"Inferred v: {model_infer.v.numpy():.4f}")

epochs = 2000
for epoch in range(epochs):
  with tf.GradientTape() as loss_tape:
    with tf.GradientTape(persistent=True) as tape2:
      tape2.watch(X_tf)
      tape2.watch(T_tf)
      with tf.GradientTape(persistent=True) as tape1:
        tape1.watch(X_tf)
        tape1.watch(T_tf)
        inputs = tf.concat([X_tf, T_tf], axis=1)
        u_pred = model_infer(inputs)
      u_x = tape1.gradient(u_pred, X_tf)
      u_t = tape1.gradient(u_pred, T_tf)
      del tape1
    del tape2
    residual = u_t + model_infer.v * u_x
    loss_pde = tf.reduce_mean(tf.square(residual))
    loss_data = tf.reduce_mean(tf.square(u_pred - u_tf))
    loss = loss_pde + loss_data

  grads = loss_tape.gradient(loss, model_infer.trainable_variables)
  optimizer.apply_gradients(zip(grads, model_infer.trainable_variables))
  if epoch % 200 == 0:
    if u_t is None or u_x is None:
      print(f"Epoch {epoch}: Error! Gradients are None. Check tape.watch().")
      break
    print(f"Epoch {epoch}: Loss {loss.numpy():.4e}, Inferred v {model_infer.v.numpy():.4f}")

print("-" * 30)
print(f"True v: {v_true}")
print(f"Inferred v: {model_infer.v.numpy():.4f}")

"""## 2.3. 1D Wave Equation

Given the data from $u_tt = c^2 u_xx$, infer $c$ from the data.

Generate the data from $c=1$, $u(x,0)=\sin(\pi x)$, $u_t=0$, $u(0,t)=0$, $u(1,t)=0$.
"""

import tensorflow as tf
import numpy as np

# Generate synthetic data
c_true = 1.0

# Creating a 20x20 grid
x_space = np.linspace(0, 1, 20)
t_space = np.linspace(0, 1, 20)
X, T = np.meshgrid(x_space, t_space)
u_data = np.sin(np.pi * X) * np.cos(np.pi * c_true * T)

# Flattening the grid data
X_flat = X.flatten()[:, None]
T_flat = T.flatten()[:, None]
u_flat = u_data.flatten()[:, None]

# Converting to the tensors
X_tf = tf.convert_to_tensor(X_flat, dtype=tf.float32)
T_tf = tf.convert_to_tensor(T_flat, dtype=tf.float32)
u_tf = tf.convert_to_tensor(u_flat, dtype=tf.float32)

# Neural Network for inference
class InferModel(tf.keras.Model):
  def __init__(self):
    super(InferModel, self).__init__()
    self.dense1 = tf.keras.layers.Dense(20, activation='tanh', kernel_initializer='glorot_normal')
    self.dense2 = tf.keras.layers.Dense(20, activation='tanh', kernel_initializer='glorot_normal')
    self.dense3 = tf.keras.layers.Dense(1)
    self.c = self.add_weight(
        name = 'c_wave_speed',
        shape = (),
        initializer = tf.keras.initializers.Constant(0.5),
        trainable = True,
        dtype = tf.float32
    )

  def call(self, inputs):
    x = self.dense1(inputs)
    x = self.dense2(x)
    return self.dense3(x)

# Training to infer c
model_infer = InferModel()
optimizer = tf.keras.optimizers.Adam(learning_rate = 0.001)

epochs = 2000
for epoch in range(epochs):
    with tf.GradientTape() as loss_tape:
        with tf.GradientTape(persistent=True) as tape2:
            tape2.watch(X_tf)
            tape2.watch(T_tf)
            with tf.GradientTape(persistent=True) as tape1:
                tape1.watch(X_tf)
                tape1.watch(T_tf)
                inputs = tf.concat([X_tf, T_tf], axis=1)
                u_pred = model_infer(inputs)

            # --- Calculate first derivatives ---
            u_x = tape1.gradient(u_pred, X_tf)  # du/dx
            u_t = tape1.gradient(u_pred, T_tf)  # du/dt
            del tape1 # Free up tape1

        # --- Calculate second derivatives ---
        u_xx = tape2.gradient(u_x, X_tf)  # d^2u/dx^2
        u_tt = tape2.gradient(u_t, T_tf)  # d^2u/dt^2
        del tape2 # Free up tape2

        # --- Check for errors ---
        if u_tt is None or u_xx is None:
            print("Error: Gradients are None. Check tape.watch().")
            break

        residual = u_tt - tf.square(model_infer.c) * u_xx
        loss_pde = tf.reduce_mean(tf.square(residual))
        loss_data = tf.reduce_mean(tf.square(u_pred - u_tf))
        loss = loss_pde + loss_data
    grads = loss_tape.gradient(loss, model_infer.trainable_variables)
    optimizer.apply_gradients(zip(grads, model_infer.trainable_variables))

    if epoch % 200 == 0:
        print(f"Epoch {epoch}: Loss {loss.numpy():.4e}, Inferred c {model_infer.c.numpy():.4f}")

print("-" * 30)
print(f"True c: {c_true}")
print(f"Inferred c: {model_infer.c.numpy():.4f}")

# Modify the hyper parameter combinations to improve the accuracy of approximating nearer to true value

epochs = 2000
for epoch in range(epochs):
    with tf.GradientTape() as loss_tape:
        with tf.GradientTape(persistent=True) as tape2:
            tape2.watch(X_tf)
            tape2.watch(T_tf)
            with tf.GradientTape(persistent=True) as tape1:
                tape1.watch(X_tf)
                tape1.watch(T_tf)
                inputs = tf.concat([X_tf, T_tf], axis=1)
                u_pred = model_infer(inputs)

            # --- Calculate first derivatives ---
            u_x = tape1.gradient(u_pred, X_tf)  # du/dx
            u_t = tape1.gradient(u_pred, T_tf)  # du/dt
            del tape1 # Free up tape1

        # --- Calculate second derivatives ---
        u_xx = tape2.gradient(u_x, X_tf)  # d^2u/dx^2
        u_tt = tape2.gradient(u_t, T_tf)  # d^2u/dt^2
        del tape2 # Free up tape2

        # --- Check for errors ---
        if u_tt is None or u_xx is None:
            print("Error: Gradients are None. Check tape.watch().")
            break

        residual = u_tt - tf.square(model_infer.c) * u_xx
        loss_pde = tf.reduce_mean(tf.square(residual))
        loss_data = tf.reduce_mean(tf.square(u_pred - u_tf))
        loss = loss_pde + loss_data
    grads = loss_tape.gradient(loss, model_infer.trainable_variables)
    optimizer.apply_gradients(zip(grads, model_infer.trainable_variables))

    if epoch % 200 == 0:
        print(f"Epoch {epoch}: Loss {loss.numpy():.4e}, Inferred c {model_infer.c.numpy():.4f}")

print("-" * 30)
print(f"True c: {c_true}")
print(f"Inferred c: {model_infer.c.numpy():.4f}")



